// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYs0bYxTEOSucvS-Wi_DqOnBWUB40GfkQ',
    appId: '1:98329506216:web:02eee85342c76f30142d9d',
    messagingSenderId: '98329506216',
    projectId: 'nado-mvp-app',
    authDomain: 'nado-mvp-app.firebaseapp.com',
    storageBucket: 'nado-mvp-app.appspot.com',
    measurementId: 'G-38NZGQRVFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfspXAy1gN0FDMrF2PyVVITZg1lxjiYt4',
    appId: '1:98329506216:android:70e13574e7183d93142d9d',
    messagingSenderId: '98329506216',
    projectId: 'nado-mvp-app',
    storageBucket: 'nado-mvp-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4iLM0VLON-zIDRrHwbZKldPW9RFwoirs',
    appId: '1:98329506216:ios:5481a139f4a980bb142d9d',
    messagingSenderId: '98329506216',
    projectId: 'nado-mvp-app',
    storageBucket: 'nado-mvp-app.appspot.com',
    iosClientId:
        '98329506216-8k27d5stpehugkrru067utufseiga7nc.apps.googleusercontent.com',
    iosBundleId: 'com.example.nadoClientMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4iLM0VLON-zIDRrHwbZKldPW9RFwoirs',
    appId: '1:98329506216:ios:5481a139f4a980bb142d9d',
    messagingSenderId: '98329506216',
    projectId: 'nado-mvp-app',
    storageBucket: 'nado-mvp-app.appspot.com',
    iosClientId:
        '98329506216-8k27d5stpehugkrru067utufseiga7nc.apps.googleusercontent.com',
    iosBundleId: 'com.example.nadoClientMvp',
  );
}
